// alert('Hello');
// alert('World');

//NO SEMICOLON NEEDED AFTER LOOPS OR FUNCTIONS

// TO ENABLE ALL MODERN JAVASCRIPT FEATURES OUR CODE SHOULD START WITH 'USE STRICT';

//SEVEN TYPES OF VARIABLES
//NUMBERS
//STRINGS
//BOOLEAN
//NULL
//UNDEFINED
//OBJECT
//SYMBOL

//typeOf returns the type of a value.
